### PR TITLE
added nsg rule for app gateway

### PR DESCRIPTION
**Pull request by faraday23**
- reorganized rules based on inbound/outbound
- added required NSG rule for application gateway
- *note* priority for NSG rule was referenced from https://github.com/openrba/python-azure-nsg-priority
@dutsmiller

### CODE REVIEW

**Comment by faraday23** [comment]
this rule is required when setting up a vnet with application gateway. because otherwise it will throw this error:

**network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0
Original Error: Code="ApplicationGatewaySubnetOutboundTrafficBlockedByNetworkSecurityGroup"**

**Comment by faraday23** [comment]
tested and verified @dutsmiller

**Comment by dutsmiller** [comment]
I think this is the wrong way to fix the module.  There are specific requirements for each "special" subnet type.  It might be best if we just don't set NSG rules for them at all.  I'll probably put in a different PR to address this.

**Comment by dutsmiller** [comment]
@faraday23  How about this:  https://github.com/Azure-Terraform/terraform-azurerm-virtual-network/pull/21

**Pull request closed without merging**
