### PR TITLE
Aks subnets nsgs

### PR DESCRIPTION
**Pull request by dutsmiller**
* Additional details for aks_subnets output.
* overdue terraform formatting

### CODE REVIEW

**Comment by dutsmiller** [comment]
@fabiendelpierre I was looking for an opinion on the layout of the output.   The route_table_id wasn't nested in each subnet to demonstrate that the route table must be the same for both of them.  However, the same could be said for vnet name/id.

**Comment by fabiendelpierre** [comment]
Does the route table have to be the same for both AKS subnets? Here's a scenario:

- Internal load balancer with private IP in private subnet
- Private subnet is peered to on-prem via ExpressRoute
- Private subnet needs route to on-prem but we don't want that route applied to the public subnet, so we need two route tables, one per subnet

Is that not feasible while still keeping AKS functional?

**Comment by dutsmiller** [comment]
Yes, the route table must be the same for all subnets.  See "Limitations" here:

https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#bring-your-own-subnet-and-route-table-with-kubenet

"Each AKS cluster must use a single, unique route table for all subnets associated with the cluster. You cannot reuse a route table with multiple clusters due to the potential for overlapping pod CIDRs and conflicting routing rules."

**Comment by fabiendelpierre** [comment]
It makes sense not to share a route table between AKS clusters but I'd think the simple scenario I proposed would be supported... but I guess nothing should surprise me anymore?

**Comment by fabiendelpierre** [comment]
Well anyway, I'm not a fan of the vnet id and name being included with every subnet since they're necessarily in the same vnet, as you mentioned. Same applies to the regular `subnets` output. Otherwise I guess this is fine?

**Pull request merged**
